
 

export const C_FIELD = 'FIELD_VALUE_UPDATE';


export const C_CELLPHONEBILL_TEXT_CHANGE = 'CELLPHONEBILL_TEXT_CHANGE';
export const C_CELLPHONEBILL_SLIDER_CHANGE = 'CELLPHONEBILL_SLIDER_CHANGE';
export const C_CELLPHONEBILL_EDITABLE_CHANGE = 'CELLPHONEBILL_EDITABLE_CHANGE';


export const C_GROCERIESANDDINING_TEXT_CHANGE = 'GROCERIESANDDINING_TEXT_CHANGE';
export const C_GROCERIESANDDINING_SLIDER_CHANGE  = 'GROCERIESANDDINING_SLIDER_CHANGE';
export const C_GROCERIESANDDINING_EDITABLE_CHANGE = 'GROCERIESANDDINING_EDITABLE_CHANGE';

export const C_UTILITIES_TEXT_CHANGE = 'UTILITIES_TEXT_CHANGE';
export const C_UTILITIES_SLIDER_CHANGE = 'UTILITIES_SLIDER_CHANGE' ;
export const C_UTILITIES_EDITABLE_CHANGE = 'UTILITIES_EDITABLE_CHANGE' ;

export const C_INSURANCE_TEXT_CHANGE = 'INSURANCE_TEXT_CHANGE' ;
export const C_INSURANCE_SLIDER_CHANGE = 'INSURANCE_SLIDER_CHANGE' ;
export const C_INSURANCE_EDITABLE_CHANGE = 'INSURANCE_EDITABLE_CHANGE' ;
export const C_INIT_INSURANCE_CHANGE = 'INIT_INSURANCE_CHANGE';

export const C_TRANSPORTATION_TEXT_CHANGE = 'TRANSPORTATION_TEXT_CHANGE' ;
export const C_TRANSPORTATION_SLIDER_CHANGE = 'TRANSPORTATION_SLIDER_CHANGE' ;
export const C_TRANSPORTATION_EDITABLE_CHANGE = 'TRANSPORTATION_EDITABLE_CHANGE' ;

export const C_SUBSCRIPTIONSERVICES_TEXT_CHANGE = 'SUBSCRIPTIONSERVICES_TEXT_CHANGE' ;
export const C_SUBSCRIPTIONSERVICES_SLIDER_CHANGE = 'SUBSCRIPTIONSERVICES_SLIDER_CHANGE' ;
export const C_SUBSCRIPTIONSERVICES_EDITABLE_CHANGE = 'SUBSCRIPTIONSERVICES_EDITABLE_CHANGE' ;

export const C_OTHEREXPENSES_TEXT_CHANGE = 'OTHEREXPENSES_TEXT_CHANGE' ;
export const C_OTHEREXPENSES_SLIDER_CHANGE = 'OTHEREXPENSES_SLIDER_CHANGE' ;
export const C_OTHEREXPENSES_EDITABLE_CHANGE = 'OTHEREXPENSES_EDITABLE_CHANGE' ;

export const C_MONTHLYITEMIZEDEXPENSES_TEXT_CHANGE = 'MONTHLYITEMIZEDEXPENSES_TEXT_CHANGE';
export const C_MONTHLYITEMIZEDEXPENSES_SLIDER_CHANGE = 'MONTHLYITEMIZEDEXPENSES_SLIDER_CHANGE' ;
export const C_MONTHLYITEMIZEDEXPENSES_EDITABLE_CHANGE = 'MONTHLYITEMIZEDEXPENSES_EDITABLE_CHANGE' ;

export const C_CV_EXPENSES_TEXT_CHANGE = "CV_EXPENSES_TEXT_CHANGE";
export const C_CV_EXPENSES_SLIDER_CHANGE = "CV_EXPENSES_SLIDER_CHANGE";
export const C_CV_EXPENSES_EDITABLE_CHANGE = "CV_EXPENSES_EDITABLE_CHANGE";

 