import React from 'react';
import { StyleSheet, Text, View, ScrollView } from 'react-native';
import OpenBtns3 from '../OpenBtns3';

import styled from 'styled-components/native';
import { Linking } from 'react-native';

 

export default function ModalB() {
  return (
    <View style={styles.container}>
      
      <ScrollView>
          <Paragraph>
            <Title>Terms of Use{'\n'}{'\n'}{'\n'}</Title>
          <Subtitle>Terms and Conditions Governing the Use of Fannie Mae Mobile Applications - V.1.2
May 2020{'\n'}{'\n'}</Subtitle>
Policy Applicable to “fannie mae mobile” Application
{'\n'}{'\n'}{'\n'}
Please read the following terms and conditions (“Terms and Conditions”) very carefully. By downloading, installing or using this Fannie Mae Mobile Application (“Application,” as further defined below), you agree that the following Terms and Conditions govern your access to and use of the Application. If you do not agree with these Terms and Conditions, do not download and do not use the Application.

{'\n'}{'\n'}{'\n'}
Applicability of These Terms and Conditions
{'\n'}{'\n'}
Your access to and use of the Application, including, without limitation, any information, documents, tools, software, functionalities, materials, graphics, and icons made available through this Application, and the overall appearance of this Application, (collectively, the “Application”), are subject to the terms and conditions set forth herein. By accessing or using the Application, you, on your behalf and behalf of your relatives relying on the Application, (“You”) agree to these Terms and Conditions which shall constitute an agreement between You and Fannie Mae with respect to the subject matter hereof. You further agree to comply with any laws and regulations governing the downloading, installation, or use of the Application, including, without limitation, any usage rules set forth in the online application store terms of service.

{'\n'}{'\n'}
Updates to These Terms and Conditions
{'\n'}{'\n'}
You acknowledge and agree that Fannie Mae may, with or without notice to You, modify or amend these Terms and Conditions, including the Fannie Mae Online Privacy Notice, from time to time. Any use of the Application following the effective date of such modification or amendment will be deemed to be Your acceptance to such changes.

{'\n'}{'\n'}
Privacy Policy
{'\n'}{'\n'}
Your use of the Application is further subject to the terms and conditions of the Fannie Mae Online Privacy Notice, incorporated by reference to and part of these Terms and Conditions, and accessible in the Settings menu of the Application or at <Text style={{color: 'blue'}} onPress={()=>Linking.openURL('https://www.fanniemae.com/portal/privacy-statement.html')}>https://www.fanniemae.com/portal/privacy-statement.html</Text>. You acknowledge and agree that You have read and understood the Fannie Mae Online Privacy Notice and that, by accessing or using the Application, You agree to such terms which shall be part of the this agreement between You and Fannie Mae with respect to the subject matter thereof.

{'\n'}{'\n'}
License Rights
{'\n'}{'\n'}
Subject to the terms and conditions set forth herein, Fannie Mae hereby grants You a non-exclusive, limited, royalty-free, and revocable license to use the Application for Your personal and non-commercial use. Any other use by You would require prior written consent of Fannie Mae. Under these Terms and Conditions You may not: (i) modify, create derivative works from, distribute, publicly display, publicly perform, or sublicense the Application; (ii) distribute or use the Application in any way that allows third parties to access or use the Application independently from Fannie Mae-approved distribution channels; or (iii) reverse engineer, decompile, disassemble, take any action to circumvent, compromise or defeat any security measures implemented in the Application or otherwise attempt to derive any of the Application’s source or object code or other contents.

{'\n'}{'\n'}
Limitations of Application Output
{'\n'}{'\n'}
Your acknowledge and agree that the Application is provided to You for information purposes only and is not to be construed as a offering a transactional platform or functionalities the use of which would in any way bind Fannie Mae or any third party. The outputs and guidance provided by the Application, although believed by Fannie Mae to be reliable, are for information and guidance only, and do not constitute housing, financial, or legal advice sufficient to substantiate any housing purchase or mortgage decision by You. As stated below, Fannie Mae makes no representation or warranty as to the completeness or accuracy of the output and guidance generated by the Application; it is Fannie Mae’s recommendation that You validate such output or guidance on the basis of housing, finance, or legal professional advice sought by You an based on the specifics of Your financial and personal situation prior to making any such decision.

{'\n'}{'\n'}
Ownership and Reservation of Rights
{'\n'}{'\n'}
The Application is the property of Fannie Mae or used under license. Fannie Mae does not waive any of its proprietary rights therein including, but not limited to, copyrights, trademarks, and other intellectual property rights. The availability of the Application shall under no circumstance constitute a transfer of any copyrights, trademarks, or other intellectual property rights of Fannie Mae or its licensors to You or any third party. The Application is protected by U.S. and international copyright laws. You may not delete any copyright or similar notice from the Application. Unauthorized attempts to extract any or all elements of the Application, or otherwise alter them, or to access Fannie Mae’s or third parties’ servers hosting the Application, are strictly prohibited, would constitute unauthorized access and/or access in excess of authorization, and may be subject to prosecution. You are not granted any trademark license in the name of, slogan or logos pertaining to, the Application for use in commerce.

{'\n'}{'\n'}
Termination
{'\n'}{'\n'}
You may terminate this agreement at Your sole discretion, for convenience, without notice and without any liability to Fannie Mae subject to the removal of the Application from Your device(s) on which the Application has been installed. Fannie Mae may terminate support and maintenance of the Application, remove the Application from online application stores or other distribution channels, alter or remove some or all of the Application’s functionalities, and may altogether terminate the license granted herein, at its sole discretion, for convenience, without notice and without any liability to You.

{'\n'}{'\n'}
Exclusion of warranty and limitation of Liability
{'\n'}{'\n'}
THE APPLICATION IS PROVIDED "AS IS." FANNIE MAE MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND WHATSOEVER FOR, AND DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES RELATED TO, THE APPLICATION, ITS OUTPUT AND RESULTS, OR ANY THIRD PARTY CONTENTS, MATERIALS OR SOFTWARE OF ANY SORTS AND RELATED OUTPUT OR GUIDANCE, WEB SITES OR ANY PRODUCTS OR SERVICES MENTIONED OR OFFERED IN OR REFERRED TO OR IN CONNECTION WITH IN THE APPLICATION, INCLUDING BUT NOT LIMITED TO THE ONLINE APPLICATION STORE YOU USED TO ACCESS AND DOWNLOAD THE APPLICATION (“THIRD PARTY CONTENTS”), INCLUDING, WITHOUT LIMITATION, WARRANTIES OF MERCHANTABILITY, SUITABILITY, NON-INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE.
{'\n'}{'\n'}
FANNIE MAE SHALL NOT BE LIABLE FOR ANY ERRORS GENERATED BY THE APPLICATION OR THIRD PARTY CONTENTS OR OTHERWISE CONTAINED THEREIN OR FOR ANY DAMAGES WHATSOEVER ARISING OUT OF OR RELATED TO THE USE OF THE APPLICATION (INCLUDING ALL THIRD PARTY CONTENTS, MATERIALS OR SOFTWARE OF ANY SORTS, WEB SITES OR ANY PRODUCTS OR SERVICES MENTIONED OR OFFERED IN OR REFERRED TO IN THE APPLICATION, INCLUDING THIRD PARTY SOFTWARE, CODE OR MALWARE THAT INCLUDES HARMFUL OR UNDISCLOSED ELEMENTS INTENDED TO DISRUPT, DISABLE, HARM, OR OTHERWISE IMPEDE THE OPERATION OF THE APPLICATION AND/OR YOUR DEVICES OR TO GAIN UNAUTHORIZED ACCESS TO YOUR DEVICE, SUCH AS COMPUTER “VIRUSES” OR “WORMS”); OR THE INABILITY TO USE THE SAME, INCLUDING, WITHOUT LIMITATION, DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, WHETHER UNDER A CONTRACT, TORT OR ANY OTHER THEORY OF LIABILITY, EVEN IF FANNIE MAE IS AWARE OF THE POSSIBILITY OF SUCH ERRORS OR DAMAGES. NOTHING IN THESE TERMS OF USE IS INTENDED TO EXCLUDE OR LIMIT ANY CONDITION, WARRANTY, RIGHT OR LIABILITY WHICH MAY NOT BE LAWFULLY EXCLUDED OR LIMITED. ONLY THE ABOVE LIMITATIONS WHICH ARE LAWFUL IN YOUR JURISDICTION WILL APPLY TO YOU AND FANNIE MAE’S LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.
{'\n'}{'\n'}
The Application is further subject to change without notice. Fannie Mae expressly disclaims any obligation to keep the Application up to date or free of errors or viruses, or to maintain uninterrupted access to the Application.

{'\n'}{'\n'}
Indemnity
{'\n'}{'\n'}
You agree to hold harmless and indemnify Fannie Mae and its subsidiaries, affiliates, officers, agents, and employees (and their subsidiaries, affiliates, officers, agents, and employees) from and against any claim, suit or action arising from or in any way related to Your use of the Application or Your violation of these Terms and Conditions, including any liability or expense arising from all claims, losses, damages, suits, judgments, litigation costs and attorneys' fees, of every kind and nature.

{'\n'}{'\n'}
Unsolicited Ideas
{'\n'}{'\n'}
Fannie Mae is not obligated to anyone disclosing unsolicited ideas about products and services to Fannie Mae personnel. Absent any written agreement to that effect, Your disclosure of ideas to Fannie Mae to improve or modify the Application or for new products, enhancements, features, innovations or inventions, or of any ideas of any sort that may be related to the Application, its subject matter, or Fannie Mae's business (“Idea”), is subject to the following: Fannie Mae is in no way obligated to You in connection with Your Idea, Fannie Mae is not obligated to keep Your Idea confidential, Your Idea will become the property of Fannie Mae should it elect to implement it or share it with third parties, and Fannie Mae is not obligated to compensate You nor has any duty to account to You should Fannie Mae elect to share or implement Your Idea.

{'\n'}{'\n'}
User Generated Contents; Social Media
{'\n'}{'\n'}
Should the Application offer the functionality for You to publicly contribute Your contents through external media, such as Social Media platforms, (“User Generated Contents”), You agree that Your User Generated Contents shall comply with the relevant terms and conditions and guidelines governing the use of such media platform and that You shall not contribute User Generated Contents that: (i) are factually erroneous or misleading, (ii) are offensive, defamatory, libelous, threatening, harassing, abusive, hateful, or inappropriate in any way, (iii) threaten the privacy rights of another, (iv) infringe on intellectual property and proprietary rights of another, or the publication of which would violate the same, or (v) violate any laws or regulations. With respect to media platforms controlled by Fannie Mae, Fannie Mae does not commit to reviewing all User Generated Contents but reserves, however, the right to block or remove in its sole discretion User Generated Contents, or disable access privilege to users who submit User Generated Contents that violate the foregoing requirements. Personal information contained in User Generated Contents is subject to the Fannie Mae Online Privacy Notice. Fannie Mae shall have otherwise no liability or obligation with respect to User Generated Contents posted on Fannie Mae-controlled media platforms may freely copy, adapt, distribute, publish, or otherwise use such User Generated Contents without any duty to account.

{'\n'}{'\n'}
Fannie Mae Guides
{'\n'}{'\n'}
To the extent the Application gives You access to the Single-Family Selling Guide, Servicing Guide, Selling and Servicing Guide Forms, Announcements, Lender Letters, and Notices, and the Multifamily Lender Memos relevant to the Multifamily Guide(s) (defined herein as the "Licensed Guides"), updated and published, from time to time, by Fannie Mae, You agree to the following: in addition to Fannie Mae, Mortgage Resource Center, Inc. ("MRC") is the exclusive publisher of electronic versions of the Licensed Guides through the AllRegs® platform. As a result You may not use deep links (i.e., links that connect directly to a page of the Licensed Guides), frame or otherwise link, or provide users of your Web site direct access to pages of the Licensed Guides as posted by Fannie Mae on this Fannie Mae Web site (together with deep linking, "Linking") to the extent such Linking would materially affect MRC's publication rights. For the avoidance of doubt, (i) You may download and reproduce the Licensed Guides as posted on this Application for Your own internal business purposes, provided that You do not reproduce, publish, distribute or otherwise make an electronic version of the Licensed Guides available to third parties, and (ii) incidental, non-systematic, Linking in support of industry news reporting, research, analysis, or commentary shall not be deemed prohibited hereunder either.

{'\n'}{'\n'}
Applicable Laws
{'\n'}{'\n'}
Fannie Mae, or its service providers as applicable, provides the Application from the United States of America. Fannie Mae makes no representation that the Application is appropriate or available for use in other locations, and access to the Application from jurisdictions where such access is illegal is prohibited. Those who choose to access and download the Application do so on their own initiative and are responsible for compliance with applicable laws of their jurisdictions. The Application or certain portions thereof may be subject to U.S. export controls and may not be downloaded, exported or re-exported into, or to a national or resident of, a country subject to trade sanctions imposed by the United States prohibiting the shipment of goods. These Terms and Conditions will be construed in accordance with the laws of the District of Columbia, United States of America, without regard to its conflict of law provisions.

{'\n'}{'\n'}
Survival
{'\n'}{'\n'}
Sections titled “Exclusion of warranty and limitation of Liability,” “Indemnity,” “Ownership and Reservation of Rights,” “User Generated Contents; Social Media,” “Unsolicited Ideas,” and “Applicable Laws,” shall survive the termination of these Terms and Conditions for any reason.

{'\n'}{'\n'}
Entire Agreement
{'\n'}{'\n'}
These Terms and Conditions and related pages set forth the entire agreement between Fannie Mae and You with respect to the subject matter hereof and supersedes all prior or contemporaneous writings, negotiations, and discussions with respect thereto.
 
{'\n'}{'\n'}
Copyright Notice
{'\n'}{'\n'}

The Application and these Terms, Copyright © 2015 Fannie Mae, all rights reserved.
          </Paragraph>
      </ScrollView>
      <OpenBtns3 />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    margin: 50,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
});


const Paragraph = styled.Text`
padding-vertical: 10px;
padding-horizontal: 10px;
`
const TermsScroll = styled.ScrollView`
padding-vertical: 10px;
padding-horizontal: 10px;
`

const Title = styled.Text`
align-items: center;
font-weight: bold;
font-size: 20px;
`

const Subtitle = styled.Text`
align-items: center;
font-weight: bold;
font-size: 15px;
`