export const COUNTER_CHANGE = 'COUNTER_CHANGE';

// notes
export const ADD_NOTE = 'ADD_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';


// calculator UI
export const SLIDER_GROSS_INCOME_CHANGE = 'SLIDER_GROSS_INCOME_CHANGE';
export const GROSS_INCOME_CHANGE = 'GROSS_INCOME_CHANGE';
export const GROSS_INCOME_RANGE_CHANGE = 'GROSS_INCOME_RANGE_CHANGE';

export const SLIDER_PAY_DEDUCTIONS_CHANGE = 'SLIDER_PAY_DEDUCTIONS_CHANGE';
export const PAY_DEDUCTIONS_CHANGE = 'PAY_DEDUCTIONS_CHANGE';

export const SLIDER_EXPENSES_CHANGE = 'SLIDER_EXPENSES_CHANGE';
export const EXPENSES_CHANGE = 'EXPENSES_CHANGE';

export const SLIDER_DEBT_CHANGE='SLIDER_DEBT_CHANGE';
export const DEBT_CHANGE = 'DEBT_CHANGE';

export const SLIDER_SAVINGS_CHANGE='SLIDER_SAVINGS_CHANGE';
export const SAVINGS_CHANGE = 'SAVINGS_CHANGE';

export const RENT_AMOUNT_CHANGE = 'RENT_AMOUNT_CHANGE';
export const LEFTOVER_CHANGE = 'LEFTOVER_CHANGE';

// checklist
export const ADD_CHECKLIST_NOTE = "ADD_CHECKLIST_NOTE";

export const PERCENT_INCOME_CHANGE = 'PERCENT_INCOME_CHANGE';

export const ARC_SEGMENT_1_BEGIN = 'ARC_SEGMENT_1_BEGIN';
export const ARC_SEGMENT_1_END = 'ARC_SEGMENT_1_END';

export const ARC_SEGMENT_2_BEGIN = 'ARC_SEGMENT_2_BEGIN';
export const ARC_SEGMENT_2_END = 'ARC_SEGMENT_2_END';

export const ARC_SEGMENT_3_BEGIN = 'ARC_SEGMENT_3_BEGIN';
export const ARC_SEGMENT_3_END = 'ARC_SEGMENT_3_END';

export const ARC_SEGMENT_4_BEGIN = 'ARC_SEGMENT_4_BEGIN';
export const ARC_SEGMENT_4_END = 'ARC_SEGMENT_4_END';

export const ARC_SEGMENT_5_BEGIN = 'ARC_SEGMENT_5_BEGIN';
export const ARC_SEGMENT_5_END = 'ARC_SEGMENT_5_END';

export const ARC_SEGMENT_6_BEGIN = 'ARC_SEGMENT_6_BEGIN';
export const ARC_SEGMENT_6_END = 'ARC_SEGMENT_6_END';

// calculations support

// export const CALC_RENT_AMOUNT = 'CALC_RENT_AMOUNT';
export const CALC_MONTHLY_EXPENSES = 'CALC_MONTHLY_EXPENSES';
export const CALC_MONTHLY_MANDATORY_DEDUCTIONS = 'CALC_MONTHLY_MANDATORY_DEDUCTIONS';
export const CALC_MONTHLY_DEBT = 'CALC_MONTHLY_DEBT';
export const CALC_MONTHLY_SAVINGS = 'CALC_MONTHLY_SAVINGS';
export const CALC_MONTHLY_LEFTOVER = 'CALC_MONTHLY_LEFTOVER';
export const CALC_RENT_AMOUNT = 'CALC_RENT_AMOUNT';

 


export const SLIDER_GROCERIESANDDINING_CHANGE = 'SLIDER_GROCERIESANDDINING_CHANGE';
export const SLIDER_UTILITIES_CHANGE = 'SLIDER_UTILITIES_CHANGE';
export const SLIDER_INSURANCE_CHANGE = 'SLIDER_INSURANCE_CHANGE';
export const SLIDER_TRANSPORTATION_CHANGE = 'SLIDER_TRANSPORTATION_CHANGE';
export const SLIDER_SUBSCRIPTIONSERVICES_CHANGE = 'SLIDER_SUBSCRIPTIONSERVICES_CHANGE';
export const SLIDER_OTHEREXPENSES_CHANGE = 'SLIDER_OTHEREXPENSES_CHANGE';
export const SLIDER_CELLPHONEBILL_CHANGE = 'SLIDER_CELLPHONEBILL_CHANGE';
export const SLIDER_MONTHLYITEMIZEDEXPENSES_CHANGE = 'SLIDER_MONTHLYITEMIZEDEXPENSES_CHANGE';
 
export const GROCERIESANDDINING_CHANGE = 'GROCERIESANDDINING_CHANGE';
export const UTILITIES_CHANGE = 'UTILITIES_CHANGE';
export const INSURANCE_CHANGE = 'INSURANCE_CHANGE';
export const TRANSPORTATION_CHANGE = 'TRANSPORTATION_CHANGE';
export const SUBSCRIPTIONSERVICES_CHANGE = 'SUBSCRIPTIONSERVICES_CHANGE';
export const OTHEREXPENSES_CHANGE = 'OTHEREXPENSES_CHANGE';
export const CELLPHONEBILL_CHANGE = 'CELLPHONEBILL_CHANGE';
export const MONTHLYITEMIZEDEXPENSES_CHANGE = 'MONTHLYITEMIZEDEXPENSES_CHANGE';

